import type { SteamEventCategory } from "@/domain/calendar/config";

export type UiLanguage = "en" | "zh";

export type LanguageOption = {
  code: string;
  label: string;
  steamLang: string;
  uiLang: string;
  uiLanguage: UiLanguage;
};

export const WEEKDAY_LABELS = {
  en: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  zh: ["日", "一", "二", "三", "四", "五", "六"],
} satisfies Record<UiLanguage, string[]>;

export const LANGUAGE_OPTIONS = [
  {
    code: "en",
    label: "English",
    steamLang: "english",
    uiLang: "en",
    uiLanguage: "en",
  },
  {
    code: "zh-CN",
    label: "简体中文",
    steamLang: "schinese",
    uiLang: "zh-CN",
    uiLanguage: "zh",
  },
] as const satisfies readonly LanguageOption[];

export const STEAM_EVENT_CATEGORY_LABELS = {
  en: {
    seasonal: {
      title: "Seasonal sales",
      description: "Summer, Autumn, Winter, and Spring sale windows",
    },
    next_fest: {
      title: "Next Fest",
      description: "Official demo festivals for upcoming games",
    },
    fest: {
      title: "Theme fests",
      description: "Genre and theme events such as bullet heaven or deckbuilders",
    },
    store_sale: {
      title: "Publisher & franchise sales",
      description: "Limited-time sales organized around a publisher, franchise, or partner",
    },
  },
  zh: {
    seasonal: {
      title: "季节促销",
      description: "春促、夏促、秋促、冬促等官方促销窗口",
    },
    next_fest: {
      title: "新品节",
      description: "面向即将推出游戏的官方试玩节",
    },
    fest: {
      title: "主题游戏节",
      description: "按类型或主题组织的 Steam 活动，例如牌组构筑或弹幕天堂",
    },
    store_sale: {
      title: "发行商与系列促销",
      description: "围绕发行商、系列作品或合作伙伴组织的限时促销",
    },
  },
} satisfies Record<UiLanguage, Record<SteamEventCategory, { description: string; title: string }>>;

export const UI_COPY = {
  en: {
    productName: "Steam to Calendar",
    positioning: "Track Steam deals, game launch dates, and events in your calendar",
    positioningShort: "Track Steam deals, launches, and events in your calendar",
    introBody:
      "Follow specific games, import a public wishlist, choose Steam sales and fests, then subscribe from Apple Calendar, Google Calendar, Outlook, or Fantastical.",
    introPrimary: "Start tracking",
    infoLabel: "About Steam to Calendar",
    addApple: "Add to Apple Calendar",
    addToCalendar: "Add to Calendar",
    createCalendarTitle: "Create your Steam calendar",
    createCalendarSubtitle: "Build it from Steam events, tracked games, or your public wishlist",
    starterPreviewEyebrow: "Starter preview",
    starterPreviewTitle: "Make this your Steam calendar",
    starterPreviewBody:
      "The preview starts with a small demo list. Import your public wishlist or add games to turn it into your own feed.",
    nextActionImportWishlist: "Import wishlist",
    nextActionAddGames: "Add games",
    nextActionSubscribe: "Subscribe",
    nextActionSubscribeHint: "Ready when these events look right",
    calendarSetupTitle: "Build your calendar",
    calendarSetupSubtitle: "Follow the steps to get started",
    mobileBuildCta: "Build calendar",
    calendarReadyTitle: "Calendar ready",
    connectWishlistTitle: "Connect Steam wishlist",
    connectWishlistDescription: "Auto-sync releases, discounts, and preorders",
    connectWishlistButton: "Connect wishlist",
    disconnectWishlist: "Disconnect wishlist",
    connectedSteamUser: "Connected user",
    connectedSteamUserFallback: "Steam user",
    wishlistGamesPrefix: "",
    wishlistGamesSuffix: " wishlist games",
    wishlistGamesListLabel: "Wishlist games",
    manualGamesTitle: "Manual list",
    manualGamesDescription: "Search and add games manually",
    trackedGamesSetupDescription: "Add games to track in your calendar",
    recommendedLabel: "Recommended",
    includedLabel: "Included",
    excludedLabel: "Off",
    orLabel: "or",
    calendarSummaryEvents: "calendar events",
    calendarSummaryGames: "tracked games",
    calendarSummaryWishlist: "wishlist connected",
    calendarSummarySteamEvents: "Steam events on",
    calendarSources: "Track",
    hotDealsTitle: "Tracked Game Deals",
    hotDealsDescription: "Top sellers that are currently discounted or available to preorder",
    trackedGameEventsTitle: "Tracked Game Events",
    eventDetailsTitle: "Details",
    itemsLabel: "Items",
    steamEventsTitle: "Steam Events",
    steamEventsDescription: "Official sale windows, Next Fest, theme fests, and publisher events",
    eventTypesTitle: "Event types",
    eventTypesNone: "No event types selected",
    pastDays: "Past days",
    saleStartedLabel: "Started",
    historicalLowLabel: "Historical low",
    saleStoreLabel: "Store",
    saleStatusLabel: "Sale status",
    historicalCurrencyMismatchNote:
      "This historical price source does not provide the selected store currency, so this event uses the source currency.",
    nextDays: "Next days",
    myGamesTitle: "Tracked Games",
    myGamesDescription:
      "Follow specific games, then connect a public Steam wishlist when you want it to replace manual picks",
    languageLabel: "Language",
    settingsLabel: "Settings",
    storeCurrencyLoading: "loading",
    storeRegionLabel: "Store region",
    storeNote: "Store region affects prices, not language",
    githubLinkLabel: "GitHub",
    blogLinkLabel: "Blog",
    donateLinkLabel: "Buy me a coffee",
    searchPlaceholder: "Search or paste URL",
    searchButton: "Search",
    searchingButton: "Searching...",
    searchResultsTitle: "Steam search results",
    searchResultsCount: "results",
    noSearchResults: "No Steam games found",
    priceUnavailable: "Price unavailable",
    wishlistRateLimitedError: "Steam is rate limiting wishlist requests.",
    wishlistRateLimitedHint:
      "Wait a few minutes, then try again. You can still keep Steam events or add games manually.",
    wishlistPrivateHint:
      "Wishlist unavailable. Make sure the wishlist is public, or add games manually for now.",
    wishlistInvalidInputError: "This does not look like a Steam profile we can read.",
    wishlistInvalidInputHint:
      "Paste a SteamID64, a /profiles/ URL, an /id/ custom URL, or a Steam wishlist URL.",
    wishlistFetchFailedError: "Steam did not return this wishlist.",
    wishlistFetchFailedHint:
      "This is often temporary. Try the full profile URL, or add games manually while Steam catches up.",
    wishlistSettingsHint:
      "If this is your profile, open Steam privacy settings and make Game details public.",
    wishlistSettingsLink: "Open Steam settings",
    wishlistGenericHint: "Steam did not respond. You can keep Steam events and add games manually.",
    wishlistConnected:
      "Wishlist connected. Manual game picks are ignored while this calendar uses your Steam wishlist.",
    syncingPreview: "Syncing your calendar preview with Steam data...",
    trendingNow: "Trending now",
    addedToCalendar: "Added to calendar",
    addedGamesLabel: "Added games",
    addedToast: "Added to calendar",
    added: "Added",
    add: "Add",
    undo: "Undo",
    remove: "Remove",
    steamProfilePlaceholder: "Paste SteamID64 or profile URL",
    steamProfileAcceptedInputs: "Accepts SteamID64, profile URLs, custom URLs, and wishlist URLs",
    steamProfileHelpLabel: "Where to find the Steam profile URL",
    steamProfileHelpTitle: "Copy your Steam profile page URL",
    steamProfileHelpBody:
      "Click your Steam name, then copy the browser address. Custom profile URLs and wishlist URLs also work.",
    steamProfileHelpAddressLabel: "2️⃣ Copy This Address",
    steamProfileHelpClickHere: "1️⃣ Click Here",
    steamProfileHelpSteamNav: "Store Library Community",
    steamProfileHelpUserName: "YOUR NAME",
    steamProfileHelpExampleProfiles: "https://steamcommunity.com/profiles/123456",
    steamProfileHelpExampleId: "https://steamcommunity.com/id/abcd",
    importing: "Importing...",
    importWishlist: "Import Steam Wishlist",
    importWishlistShort: "Import wishlist",
    calendarCtaHint: "Apple Calendar · Google Calendar · Outlook",
    calendarManualSubscribeHint:
      "If the button does not open your calendar, copy the subscription link and add it manually",
    calendarManualSubscribeShortHint: "Or copy the ICS link and subscribe manually",
    copySubscriptionUrl: "Copy link",
    copiedSubscriptionUrl: "Copied",
    importingWishlist:
      "Reading your public Steam wishlist and preparing calendar events. This can take a moment for larger wishlists.",
    wishlistHint:
      "Connecting a public wishlist replaces manual picks and keeps future releases synced in this calendar",
    today: "Today",
    month: "Month",
    list: "List",
    syncingCalendar: "Syncing Steam calendar data...",
    noCalendarEvents: "No calendar events",
    noCalendarEventsDescription:
      "Add or enable calendar items from the left panel to preview them here",
    watchedGamePending:
      "We will keep watching this game. If Steam returns a discount or release event, it will appear on the calendar.",
    watchedReleasedGamePending:
      "We will keep watching this game. If Steam returns a discount, it will appear on the calendar.",
    watchedUnreleasedGamePending:
      "We will keep watching this game. If Steam returns a release event, it will appear on the calendar.",
    dealsLegend: "Deals",
    preordersLegend: "Preorders",
    releasesLegend: "Release",
    eventsLegend: "Fests / Events",
    salesLegend: "Sales",
    noEventsVisible: "No events visible",
    noEventsVisibleDescription: "Add or enable items from the left panel to see event details",
    steamCliEventData: "Steam CLI event data",
    until: "Until",
    dealEndsAt: "Deal ends",
    developerLabel: "Developer",
    genreLabel: "Type",
    publisherLabel: "Publisher",
    ratingLabel: "Reviews",
    releaseDateLabel: "Release",
    viewOnSteam: "View on Steam",
    footerNotice: "Steam to Calendar is not affiliated with Valve Corp.",
    footerHowItWorks: "How it works",
    footerPrivacy: "Privacy",
    footerChangelog: "Changelog",
  },
  zh: {
    productName: "Steam to Calendar",
    positioning: "在系统日历里追踪 Steam 折扣、游戏发售日和活动",
    positioningShort: "在日历里追踪 Steam 折扣、发售和活动",
    introBody:
      "关注指定游戏、导入公开愿望单、选择 Steam 促销和活动，然后订阅到 Apple Calendar、Google Calendar、Outlook 或 Fantastical。",
    introPrimary: "开始追踪",
    infoLabel: "关于 Steam to Calendar",
    addApple: "添加到 Apple 日历",
    addToCalendar: "订阅到日历",
    createCalendarTitle: "创建你的 Steam 日历",
    createCalendarSubtitle: "从 Steam 活动、关注游戏或公开愿望单生成",
    starterPreviewEyebrow: "起始预览",
    starterPreviewTitle: "把它变成你的 Steam 日历",
    starterPreviewBody:
      "当前预览先用一小组示例游戏启动。导入公开愿望单或添加游戏后，它才会变成你的订阅源。",
    nextActionImportWishlist: "导入愿望单",
    nextActionAddGames: "添加游戏",
    nextActionSubscribe: "订阅",
    nextActionSubscribeHint: "事件看起来对了就可以订阅",
    calendarSetupTitle: "构建你的日历",
    calendarSetupSubtitle: "按步骤开始设置",
    mobileBuildCta: "构建日历",
    calendarReadyTitle: "日历已准备好",
    connectWishlistTitle: "关联 Steam 愿望单",
    connectWishlistDescription: "自动同步发售、折扣和预购",
    connectWishlistButton: "关联愿望单",
    disconnectWishlist: "取消关联",
    connectedSteamUser: "已关联用户",
    connectedSteamUserFallback: "Steam 用户",
    wishlistGamesPrefix: "愿望单游戏 ",
    wishlistGamesSuffix: " 款",
    wishlistGamesListLabel: "愿望单游戏",
    manualGamesTitle: "手动列表",
    manualGamesDescription: "手动搜索并添加游戏",
    trackedGamesSetupDescription: "添加要在日历中追踪的游戏",
    recommendedLabel: "推荐",
    includedLabel: "已包含",
    excludedLabel: "关闭",
    orLabel: "或",
    calendarSummaryEvents: "个日历事件",
    calendarSummaryGames: "个关注游戏",
    calendarSummaryWishlist: "愿望单已关联",
    calendarSummarySteamEvents: "Steam 活动已开启",
    calendarSources: "追踪内容",
    hotDealsTitle: "关注游戏折扣",
    hotDealsDescription: "当前正在打折或可预购的热门 Steam 游戏",
    trackedGameEventsTitle: "关注游戏事件",
    eventDetailsTitle: "详情",
    itemsLabel: "数量",
    steamEventsTitle: "Steam 活动",
    steamEventsDescription: "Steam 官方促销窗口、新品节、主题游戏节和发行商活动",
    eventTypesTitle: "活动类型",
    eventTypesNone: "未选择活动类型",
    pastDays: "过去天数",
    saleStartedLabel: "开始",
    historicalLowLabel: "史低",
    saleStoreLabel: "商店",
    saleStatusLabel: "促销状态",
    historicalCurrencyMismatchNote:
      "这个历史价格来源没有提供当前商店币种，所以此事件按数据源返回的币种显示。",
    nextDays: "未来天数",
    myGamesTitle: "关注游戏",
    myGamesDescription: "关注指定游戏；之后也可以关联公开 Steam 愿望单来替代手动选择",
    languageLabel: "语言",
    settingsLabel: "设置",
    storeCurrencyLoading: "加载中",
    storeRegionLabel: "商店地区",
    storeNote: "商店地区影响价格，不影响界面语言",
    githubLinkLabel: "GitHub",
    blogLinkLabel: "项目博客",
    donateLinkLabel: "Buy me a coffee",
    searchPlaceholder: "关键字或粘贴链接",
    searchButton: "搜索",
    searchingButton: "搜索中...",
    searchResultsTitle: "Steam 搜索结果",
    searchResultsCount: "个结果",
    noSearchResults: "没有找到 Steam 游戏",
    priceUnavailable: "暂无价格",
    wishlistRateLimitedError: "Steam 正在限制愿望单请求。",
    wishlistRateLimitedHint: "等几分钟后再试即可。你也可以先保留 Steam 活动，或手动添加游戏。",
    wishlistPrivateHint: "愿望单暂不可用。确认愿望单是公开的，或先手动添加游戏。",
    wishlistInvalidInputError: "这个输入看起来不像可读取的 Steam 个人资料。",
    wishlistInvalidInputHint:
      "可以粘贴 SteamID64、/profiles/ 链接、/id/ 自定义链接，或 Steam 愿望单链接。",
    wishlistFetchFailedError: "Steam 没有返回这个愿望单。",
    wishlistFetchFailedHint: "这通常是临时问题。可以试试完整个人资料链接，或先手动添加游戏。",
    wishlistSettingsHint: "如果这是你的账号，打开 Steam 隐私设置，把游戏详情 / 愿望单设为公开。",
    wishlistSettingsLink: "打开 Steam 设置",
    wishlistGenericHint: "Steam 暂时没有响应。你仍然可以保留 Steam 活动并手动添加游戏。",
    wishlistConnected: "愿望单已关联。当前日历使用你的 Steam 愿望单，手动添加的游戏会被忽略。",
    syncingPreview: "正在从 Steam 同步日历预览...",
    trendingNow: "近期热门",
    addedToCalendar: "已添加到日历",
    addedGamesLabel: "已添加游戏",
    addedToast: "已添加到日历",
    added: "已添加",
    add: "添加",
    undo: "撤回",
    remove: "移除",
    steamProfilePlaceholder: "粘贴 SteamID64 或个人资料链接",
    steamProfileAcceptedInputs: "支持 SteamID64、个人资料链接、自定义链接和愿望单链接",
    steamProfileHelpLabel: "在哪里找到 Steam 个人资料链接",
    steamProfileHelpTitle: "复制你的 Steam 个人资料页链接",
    steamProfileHelpBody:
      "点击 Steam 用户名，然后复制浏览器地址栏。自定义个人主页和愿望单链接也可以。",
    steamProfileHelpAddressLabel: "2️⃣ 复制这个地址",
    steamProfileHelpClickHere: "1️⃣ 点这里",
    steamProfileHelpSteamNav: "商店 库 社区",
    steamProfileHelpUserName: "你的名字",
    steamProfileHelpExampleProfiles: "https://steamcommunity.com/profiles/123456",
    steamProfileHelpExampleId: "https://steamcommunity.com/id/abcd",
    importing: "导入中...",
    importWishlist: "导入 Steam 愿望单",
    importWishlistShort: "导入愿望单",
    calendarCtaHint: "Apple 日历 · Google 日历 · Outlook",
    calendarManualSubscribeHint: "如果按钮没有打开日历，可以复制订阅链接，在日历 App 里手动添加",
    calendarManualSubscribeShortHint: "或复制 ICS 链接并手动订阅",
    copySubscriptionUrl: "复制链接",
    copiedSubscriptionUrl: "已复制",
    importingWishlist:
      "正在读取你的公开 Steam 愿望单并准备日历事件。愿望单较大时可能需要一点时间。",
    wishlistHint: "关联公开愿望单后会替代手动选择，并让未来发售事件持续同步到这个日历",
    today: "今天",
    month: "月",
    list: "列表",
    syncingCalendar: "正在同步 Steam 日历数据...",
    noCalendarEvents: "暂无日历事件",
    noCalendarEventsDescription: "从左侧添加或开启要显示的内容后，就可以在这里预览",
    watchedGamePending: "我们会持续追踪这个游戏；如果 Steam 返回促销或发售活动，就会显示在日历里。",
    watchedReleasedGamePending: "我们会持续追踪这个游戏；如果 Steam 返回促销，就会显示在日历里。",
    watchedUnreleasedGamePending:
      "我们会持续追踪这个游戏；如果 Steam 返回发售活动，就会显示在日历里。",
    dealsLegend: "折扣",
    preordersLegend: "预购",
    releasesLegend: "发售",
    eventsLegend: "活动",
    salesLegend: "促销",
    noEventsVisible: "暂无可见事件",
    noEventsVisibleDescription: "从左侧添加或开启内容后，就会在这里显示详情",
    steamCliEventData: "Steam CLI 活动数据",
    until: "至",
    dealEndsAt: "优惠至",
    developerLabel: "开发商",
    genreLabel: "类型",
    publisherLabel: "发行商",
    ratingLabel: "好评率",
    releaseDateLabel: "发售日",
    viewOnSteam: "在 Steam 查看",
    footerNotice: "Steam to Calendar 与 Valve Corp. 没有关联。",
    footerHowItWorks: "工作方式",
    footerPrivacy: "隐私",
    footerChangelog: "更新记录",
  },
} satisfies Record<UiLanguage, Record<string, string>>;
